name: Natural Language DEX Interface Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install root dependencies
      run: npm ci

    - name: Install ElizaOS agent dependencies
      run: |
        cd natural-language-dex
        npm ci

    - name: Install test suite dependencies
      run: |
        cd natural-language-dex/tests
        npm ci

    - name: Setup environment variables
      run: |
        echo "PULSECHAIN_RPC_URL=https://rpc.pulsechain.com" >> $GITHUB_ENV
        echo "BASE_CHAIN_RPC_URL=https://mainnet.base.org" >> $GITHUB_ENV
        echo "NINMM_AGGREGATOR_BASE_URL=https://api.9mm.pro" >> $GITHUB_ENV

    - name: Run TypeScript type checking
      run: npm run type-check

    - name: Run linting
      run: npm run lint

    - name: Run API integration tests
      run: npm run test:api
      env:
        NODE_ENV: test

    - name: Run wallet functionality tests
      run: npm run test:wallet
      env:
        NODE_ENV: test

    - name: Run natural language parser tests
      run: npm run test:parser
      env:
        NODE_ENV: test

    - name: Run comprehensive test suite
      run: npm test
      env:
        NODE_ENV: test

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.node-version }}
        path: |
          natural-language-dex/tests/test-report-*.md
          natural-language-dex/tests/*.log

  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run security audit
      run: npm audit --audit-level=moderate

    - name: Check for vulnerabilities
      run: |
        cd natural-language-dex
        npm audit --audit-level=moderate

  build:
    runs-on: ubuntu-latest
    needs: [test, security]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Build ElizaOS agent
      run: |
        cd natural-language-dex
        npm ci
        npm run build 